apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2-dashboard
  namespace: production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-v2-dashboard
  template:
    metadata:
      labels:
        app: web-v2-dashboard
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: web
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

