# Default values for frontcode.
# This is a minimal values file since we are using raw manifests in templates.
replicaCount: 3

image:
  repository: 10.2.2.40:5000/library/web-v2-dashboard
  pullPolicy: Always
  tag: "latest-8"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - k8s-workernode6
